events {}

http {

    resolver 1.1.1.1 ipv6=off;

    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 5;

    upstream competition_service { server competition-service:8001; }
    upstream auth_service { server auth-service:8002; }

    server {
        listen 80;

        client_max_body_size 100M;

        location = /login {
            proxy_pass http://auth_service/login;
        }

        location = /refresh {
            proxy_pass http://auth_service/refresh;
        }

        location /test {
            access_by_lua_file /etc/nginx/lua/auth.lua;

            if ($http_x_role != "admin") {
                return 403;
            }

            proxy_pass http://competition_service/api/users;
        }

        location /challenges {
            access_by_lua_file /etc/nginx/lua/auth.lua;

            proxy_pass http://competition_service/api/challenges;
        }

        location /attempts {
            proxy_pass http://competition_service/attempts/;
        }

        location /leaderboard {
            proxy_pass http://competition_service/leaderboard/;
        }

        location /penalties {
            proxy_pass http://competition_service/penalties/;
        }

        location /scores {
            proxy_pass http://competition_service/scores/;
        }

        location /export {
            proxy_pass http://competition_service/export/;
        }

        location /drivers {
            proxy_pass http://competition_service/drivers/;
        }

        location /teams {
            proxy_pass http://competition_service/teams/;
        }

        location /users {
            proxy_pass http://auth_service/users/;
        }
    }
}
