events {}

http {
    resolver 127.0.0.11 ipv6=off valid=10s;

    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 5;

    server {
        listen 80;
        client_max_body_size 100M;

        set $auth_service auth-service:8002;
        set $competition_service competition-service:8001;

        location = /login {
            proxy_pass http://$auth_service$request_uri;
        }

        location = /refresh {
            proxy_pass http://$auth_service$request_uri;
        }

        location /test {
            access_by_lua_file /etc/nginx/lua/auth.lua;

            if ($http_x_role != "admin") {
                return 403;
            }

            proxy_pass http://$competition_service/api/users;
        }

        location /challenges {
            access_by_lua_file /etc/nginx/lua/auth.lua;

            proxy_pass http://$competition_service$request_uri;
        }

        location /attempts {
            proxy_pass http://$competition_service$request_uri;
        }

        location /leaderboard {
            proxy_pass http://$competition_service$request_uri;
        }

        location /penalties {
            proxy_pass http://$competition_service$request_uri;
        }

        location /scores {
            proxy_pass http://$competition_service$request_uri;
        }

        location /export {
            proxy_pass http://$competition_service$request_uri;
        }

        location /drivers {
            proxy_pass http://$competition_service$request_uri;
        }

        location /teams {
            proxy_pass http://$competition_service$request_uri;
        }

        location /users {
            proxy_pass http://$auth_service$request_uri;
        }
    }
}
