services:
  zec-mock-backend:
    container_name: zec-mock-backend
    build:
      context: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT_DESKTOP_APP}:${FLASK_PORT}

  zec-desktop-app-frontend:
    container_name: zec-desktop-app-frontend
    build:
      context: ./frontend/zeitnehmerapplikation
    restart: always
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT_DESKTOP_APP}:${NEXT_JS_PORT}
    environment:
      - ${NEXT_PUBLIC_DESKTOP_APP_API_URL}:${NEXT_PUBLIC_DESKTOP_APP_API_URL}

volumes:
  zec-db-data:
