version: '3.8' 
 
services: 
  db: 
    image: postgres:17 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: mydb 
    command: ["postgres", "-c", "log_statement=all"] 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 10s 
      retries: 5 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    ports: 
      - "5432:5432" 
    networks:
      - keynet

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=mydb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8090:8080"
    volumes:
      - kc_data:/opt/keycloak/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keynet
 
  adminer: 
    image: adminer 
    restart: always 
    ports: 
      - "8080:8080" 
    depends_on:
      - db
    networks:
      - keynet
 
volumes: 
  postgres_data: 
  kc_data:

networks:
  keynet: