"""innit migration

Revision ID: b4b3961f16fe
Revises: 
Create Date: 2026-05-19 17:22:30.374720

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'b4b3961f16fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
