"""add missing macs

Revision ID: fc14fb257e0b
Revises: e59a9185786e
Create Date: 2025-12-06 15:15:35.667060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc14fb257e0b'
down_revision: Union[str, Sequence[str], None] = 'e59a9185786e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('esp_mac_start1', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('esp_mac_start2', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('esp_mac_finish1', sa.String(), nullable=True))
    op.add_column('challenges', sa.Column('esp_mac_finish2', sa.String(), nullable=True))
    op.drop_column('challenges', 'esp_mac')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('esp_mac', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('challenges', 'esp_mac_finish2')
    op.drop_column('challenges', 'esp_mac_finish1')
    op.drop_column('challenges', 'esp_mac_start2')
    op.drop_column('challenges', 'esp_mac_start1')
    # ### end Alembic commands ###
