events {}

http {

    # -------------------------
    # Upstreams
    # -------------------------
    upstream auth_service {
        server auth-service:8000;
    }

    upstream challenge_service {
        server challenge-service:8001;
    }

    upstream score_service {
        server score-service:8002;
    }

    upstream team_service {
        server team-service:8003;
    }

    upstream user_service {
        server user-service:8004;
    }

    # -------------------------
    # Auth subrequest
    # -------------------------
    server {
        listen 80;

        # Standard headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;

        location = / {
        default_type application/json;
        return 200 '{"service": "CTF API Gateway", "status": "running", "endpoints": ["/auth/login", "/users/", "/teams/", "/challenges/", "/scores/"]}';
        }
        # -------- INTERNAL AUTH --------
        location = /_auth {
            internal;
            proxy_pass http://auth_service/verify;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        # -------------------------
        # AUTH SERVICE (Public)
        # -------------------------
        location /auth/login {
            proxy_pass http://auth_service/login;
        }

        # -------------------------
        # USER SERVICE (Protected)
        # -------------------------
        location /users/ {
            auth_request /_auth;
            rewrite ^/users/?(.*)$ /$1 break;
            proxy_pass http://user_service;
        }

        # -------------------------
        # TEAM SERVICE (Protected)
        # -------------------------
        location /teams/ {
            auth_request /_auth;
            rewrite ^/teams/?(.*)$ /$1 break;
            proxy_pass http://team_service;
        }

        # -------------------------
        # CHALLENGE SERVICE (Protected)
        # -------------------------
        location /challenges/ {
            auth_request /_auth;
            rewrite ^/challenges/?(.*)$ /$1 break;
            proxy_pass http://challenge_service;
        }

        # -------------------------
        # SCORE SERVICE (Public + Protected)
        # -------------------------

        # Public leaderboard
        location = /scores/leaderboard {
            rewrite ^/scores/?(.*)$ /$1 break;
            proxy_pass http://score_service;
        }

        # Everything else protected
        location /scores/ {
            auth_request /_auth;
            rewrite ^/scores/?(.*)$ /$1 break;
            proxy_pass http://score_service;
        }
    }
}
